//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hangman_The_Fun_Version.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Hangman_The_Fun_Version.Resources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Djur.
        /// </summary>
        internal static string Animals {
            get {
                return ResourceManager.GetString("Animals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Är du säker?.
        /// </summary>
        internal static string AreYouSure {
            get {
                return ResourceManager.GetString("AreYouSure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vad heter du?.
        /// </summary>
        internal static string AskForName {
            get {
                return ResourceManager.GetString("AskForName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Försök: .
        /// </summary>
        internal static string Attempts {
            get {
                return ResourceManager.GetString("Attempts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grymt jobbat! .
        /// </summary>
        internal static string Awsome {
            get {
                return ResourceManager.GetString("Awsome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tillbaka.
        /// </summary>
        internal static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bättre lycka nästa gång! .
        /// </summary>
        internal static string BetterLuckNextTime {
            get {
                return ResourceManager.GetString("BetterLuckNextTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kategori.
        /// </summary>
        internal static string Category {
            get {
                return ResourceManager.GetString("Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Djur.
        /// </summary>
        internal static string Category_Animals {
            get {
                return ResourceManager.GetString("Category_Animals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Städer.
        /// </summary>
        internal static string Category_Cities {
            get {
                return ResourceManager.GetString("Category_Cities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frukter.
        /// </summary>
        internal static string Category_Fruits {
            get {
                return ResourceManager.GetString("Category_Fruits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Städer.
        /// </summary>
        internal static string Cities {
            get {
                return ResourceManager.GetString("Cities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rensa High Score.
        /// </summary>
        internal static string ClearList {
            get {
                return ResourceManager.GetString("ClearList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Danska.
        /// </summary>
        internal static string Danish {
            get {
                return ResourceManager.GetString("Danish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Svårighetsgrad.
        /// </summary>
        internal static string Difficulty {
            get {
                return ResourceManager.GetString("Difficulty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lätt.
        /// </summary>
        internal static string Difficulty_Easy {
            get {
                return ResourceManager.GetString("Difficulty_Easy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Svårt.
        /// </summary>
        internal static string Difficulty_Hard {
            get {
                return ResourceManager.GetString("Difficulty_Hard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Normal.
        /// </summary>
        internal static string Difficulty_Normal {
            get {
                return ResourceManager.GetString("Difficulty_Normal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lätt.
        /// </summary>
        internal static string Easy {
            get {
                return ResourceManager.GetString("Easy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Du gissade på följande bokstäver: .
        /// </summary>
        internal static string EndShowGuessedLetters {
            get {
                return ResourceManager.GetString("EndShowGuessedLetters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Antal gissningar: .
        /// </summary>
        internal static string EndShowGuesses {
            get {
                return ResourceManager.GetString("EndShowGuesses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Det hemliga ordet var: .
        /// </summary>
        internal static string EndShowWord {
            get {
                return ResourceManager.GetString("EndShowWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Engelska.
        /// </summary>
        internal static string English {
            get {
                return ResourceManager.GetString("English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ange lösenord för att rensa high score: .
        /// </summary>
        internal static string EnterPassword {
            get {
                return ResourceManager.GetString("EnterPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Avsluta.
        /// </summary>
        internal static string Exit {
            get {
                return ResourceManager.GetString("Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tack för denna gången..
        /// </summary>
        internal static string ExitMessage {
            get {
                return ResourceManager.GetString("ExitMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kunde inte läsa filen.
        /// </summary>
        internal static string FileReadError {
            get {
                return ResourceManager.GetString("FileReadError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ops, något gick fel, kunde inte spara.
        /// </summary>
        internal static string FileWriteError {
            get {
                return ResourceManager.GetString("FileWriteError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frukter.
        /// </summary>
        internal static string Fruits {
            get {
                return ResourceManager.GetString("Fruits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GAME OVER!.
        /// </summary>
        internal static string GameOver {
            get {
                return ResourceManager.GetString("GameOver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tyska.
        /// </summary>
        internal static string Germany {
            get {
                return ResourceManager.GetString("Germany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gissade bokstäver: .
        /// </summary>
        internal static string GuessedLetters {
            get {
                return ResourceManager.GetString("GuessedLetters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gissa en bokstav.
        /// </summary>
        internal static string GuessLetter {
            get {
                return ResourceManager.GetString("GuessLetter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Svårt.
        /// </summary>
        internal static string Hard {
            get {
                return ResourceManager.GetString("Hard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to High Score listan är nu tömd!.
        /// </summary>
        internal static string HighScoreListIsEmpty {
            get {
                return ResourceManager.GetString("HighScoreListIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Språk.
        /// </summary>
        internal static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nej.
        /// </summary>
        internal static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Det finns inget high score än! .
        /// </summary>
        internal static string NoHighScore {
            get {
                return ResourceManager.GetString("NoHighScore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Normal.
        /// </summary>
        internal static string Normal {
            get {
                return ResourceManager.GetString("Normal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Norska.
        /// </summary>
        internal static string Norway {
            get {
                return ResourceManager.GetString("Norway", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lösenord: .
        /// </summary>
        internal static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spela.
        /// </summary>
        internal static string Play {
            get {
                return ResourceManager.GetString("Play", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tryck på valfri knapp för att fortsätta.
        /// </summary>
        internal static string Press {
            get {
                return ResourceManager.GetString("Press", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fel vid läsning av highscore: .
        /// </summary>
        internal static string ReadError {
            get {
                return ResourceManager.GetString("ReadError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ett fel uppstod vid hämtning av ord.
        /// </summary>
        internal static string RetrievingWords {
            get {
                return ResourceManager.GetString("RetrievingWords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hemliga ordet var: .
        /// </summary>
        internal static string SecretWord {
            get {
                return ResourceManager.GetString("SecretWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Namn: .
        /// </summary>
        internal static string SetName {
            get {
                return ResourceManager.GetString("SetName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to High Score.
        /// </summary>
        internal static string ShowHighScore {
            get {
                return ResourceManager.GetString("ShowHighScore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visa High Score.
        /// </summary>
        internal static string ShowList {
            get {
                return ResourceManager.GetString("ShowList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Svenska.
        /// </summary>
        internal static string Swedish {
            get {
                return ResourceManager.GetString("Swedish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Antal försök kvar: .
        /// </summary>
        internal static string TriesLeft {
            get {
                return ResourceManager.GetString("TriesLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bra jobbat!.
        /// </summary>
        internal static string WellDone {
            get {
                return ResourceManager.GetString("WellDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Felaktig inmatning. Välj mellan 1-2.
        /// </summary>
        internal static string WrongInput1_2 {
            get {
                return ResourceManager.GetString("WrongInput1-2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Felaktig inmatning. Välj mellan 1-3.
        /// </summary>
        internal static string WrongInput1_3 {
            get {
                return ResourceManager.GetString("WrongInput1-3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Felaktig inmatning. Välj mellan 1-4.
        /// </summary>
        internal static string WrongInput1_4 {
            get {
                return ResourceManager.GetString("WrongInput1-4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Felaktig inmatning. Välj mellan 1-6.
        /// </summary>
        internal static string WrongInput1_6 {
            get {
                return ResourceManager.GetString("WrongInput1-6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bokstaven finns inte.
        /// </summary>
        internal static string WrongLetter {
            get {
                return ResourceManager.GetString("WrongLetter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fel lösenord! High score-listan rensades inte!.
        /// </summary>
        internal static string WrongPassword {
            get {
                return ResourceManager.GetString("WrongPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ja.
        /// </summary>
        internal static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
